spring:
  application:
    name: shopping-system
  profiles:
    default: dev

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
